"""Write a jobs file that continues every run of a previous batch from its latest saved step.

    python make_batch_restart.py <jobs_prev.txt> <jobs_next.txt> [--skip name,name] [--only name,name]

For each job in jobs_prev.txt the newest run directory runs/batch/<name>[-cN] with saved steps becomes the
restart source; driver, case, overrides and extra args are kept.  Runs with no saved step (seed still
building) are restarted fresh.  Pass --design-step-scale changes etc. by editing the output file.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent / "runs" / "batch"

ap = argparse.ArgumentParser()
ap.add_argument("prev")
ap.add_argument("next")
ap.add_argument("--skip", default="")
ap.add_argument("--only", default="")
args = ap.parse_args()
skip = set(filter(None, args.skip.split(",")))
only = set(filter(None, args.only.split(",")))

out = ["# generated by make_batch_restart.py from " + args.prev]
for line in Path(args.prev).read_text().splitlines():
    if not line.strip() or line.startswith("#"):
        out.append(line)
        continue
    name, drv, case, ovr, extra, _src = line.split("|")
    if name in skip or (only and name not in only):
        continue
    cands = [p for p in ROOT.glob(f"{name}*") if p.is_dir() and re.fullmatch(rf"{re.escape(name)}(-c\d+)?", p.name)]
    cands = [p for p in cands if list(p.glob("wout.step*.nc"))]
    if cands:
        # the most recent continuation (highest -cN) is the most advanced run, whatever its step numbering
        latest = max(cands, key=lambda p: (int(m.group(1)) if (m := re.search(r"-c(\d+)$", p.name)) else 0, p.stat().st_mtime))
        nstep = max(int(re.search(r"step(\d+)", q.name).group(1)) for q in latest.glob("wout.step*.nc"))
        src = f"runs/batch/{latest.name}"
        print(f"{name:18s} restart from {latest.name} step {nstep}")
    else:
        src = "-"
        print(f"{name:18s} no saved step: fresh start")
    if drv == "T" and src != "-":
        # SLSQP restarts from an identity Hessian: damp the first steps of a continued run (max scale 0.2)
        import re as _re
        m = _re.search(r"--design-step-scale\s+([0-9.eE+-]+)", extra)
        scale = float(m.group(1)) if m else 0.2   # an explicit scale is a deliberate choice: keep it
        extra = _re.sub(r"--design-step-scale\s+[0-9.eE+-]+", "", extra).strip()
        extra = (extra + f" --design-step-scale {scale}").strip() if extra != "-" else f"--design-step-scale {scale}"
    out.append("|".join([name, drv, case, ovr, extra, src]))
Path(args.next).write_text("\n".join(out) + "\n")
print("wrote", args.next)
